# Generated by cpp11: do not edit by hand

random_Rt_m32 <- function(n, mu, sigma, ell, seed) {
  .Call(`_emerge_random_Rt_m32`, n, mu, sigma, ell, seed)
}

simulate_emergence <- function(R, k, generation_cdf, outcome_cdfs, seed) {
  .Call(`_emerge_simulate_emergence`, R, k, generation_cdf, outcome_cdfs, seed)
}
